### ISSUE TITLE
Add YAML config file to control accepted file formats

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#152]
The `ACCEPTED_FILE_FORMATS` setting cannot be controlled without editing the application code. The setting should be able to be controlled using a YAML file, with a format like this:

```yaml
accepted_file_formats:
    Archive:
        - zip
        - 7z
        - rar
    Document:
        - doc
        - docx
    Database:
        - db
        - sqlite3
    Photo:
        - jpg
        - jpeg
        - png
        - tiff
```
