### ISSUE TITLE
Migrate from Poetry to uv

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#544]
I've done a few tests with [uv](https://docs.astral.sh/uv/) and so far it looks like a superior tool to Poetry, and I think we should migrate from Poetry to it. It's from the same team who made [Ruff](https://docs.astral.sh/ruff/) and it looks to be as high quality as that tool is.

Benefits of `uv`:

- It's notably faster than Poetry which should help containers build quicker.
- It's already [installed in python3.10-nodejs22](https://github.com/nikolaik/docker-python-nodejs/blob/81f1181f6d57f8d743c141292c0aa17cad4204d9/Dockerfile#L30) so we don't need to install anything extra in the image.
- It's easy to [install in GitHub actions](https://docs.astral.sh/uv/guides/integration/github/#installation). It also uses a shared package cache in GitHub actions so installs should be really speedy since it won't need to download all the packages every time they're installed.
- It allows you to [specify a Python version with a .python-version file](https://docs.astral.sh/uv/concepts/python-versions/#python-version-files), and will install the required version if the system does not already have it installed. This is an important feature to ensure that everyone uses the same version of Python.

# poetry Commands vs. uv Commands

Installing packages with dev extras:

```shell
# with poetry:
poetry install --extras dev

# with uv:
uv sync --extra dev
```

Adding a new package to the dev extras:

```shell
# with poetry:
poetry add Sphinx --extras dev

# with uv:
uv add Sphinx --optional dev
```

Update lock file:

```shell
# with poetry:
poetry lock

# with uv:
uv lock
```

Bonus commands with `uv`:

```shell
# See dependency tree:
uv tree

# Pin Python version:
uv python pin 3.11
```

# Migrating

- To migrate the pyproject.toml file, it looks like this tool should do the job: https://github.com/mkniewallner/migrate-to-uv
- The documentation should have any `poetry` commands replaced with `uv`
- The `Containerfile` should use `uv` instead of `poetry`
- The GitHub actions should use the uv setup action:

  ```yaml
  # THE OLD WAY
  - name: Install pipx
     run: python -m pip install --upgrade pip && pip install pipx

  - name: Install Poetry
    run: pipx install poetry

  - name: Install dependencies
    run: poetry install --extras "dev"


  # THE NEW WAY
  - name: Install uv
    uses: astral-sh/setup-uv@v5
    with:
      version: "0.7.2"

  - name: Install dependencies
    run: uv sync --extra dev
  ```

- In the unit test container, make sure to follow [these steps for the Python version matrix](https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions).
- Use the [python-version-file:](https://docs.astral.sh/uv/guides/integration/github/#setting-up-python) setting in actions to install the same version of Python in the action container as we use locally.
- Instead of `poetry run` use `uv run` in Actions
